In [ ]:
# Index
   : In r Index of values for vector or list always starts from '1'

In [ ]:
# Supress Warnings
    options(warn=-1) 

In [ ]:
# Install package 
	install.packages("plotrix")

In [ ]:
# Call the Library
	library(plotrix)

In [ ]:
set.seed(456)

# Print Satements

In [72]:
# using print
 
 print("Hi Santhosh")

[1] "Hi Santhosh"


In [75]:
# Concatenation/ paste

x <- "Mysore"

print(paste0("Santhosh from ",x))

[1] "Santhosh from Mysore"


In [83]:
x <- "Mysore"

 # string print
    sprintf("%s is best", x)

[1] "Mysore is best"

In [86]:
    myString <- "Welcome to Programiz"

    # print formatted string
    sprintf("String: %s", myString)

[1] "String: Welcome to Programiz"

In [79]:
# Print integer values
    x1 = 255  

    sprintf("%d is integer", x1)

[1] "255 is integer"

In [87]:
    myInteger <- 123
    sprintf("Integer Value: %d", myInteger)

[1] "Integer Value: 123"

In [82]:
# float print

    x2 = 23.14  

    sprintf("%f is float", x2)

[1] "23.140000 is float"

In [84]:
# Print output using cat() function
x = "Mysore"

cat(x, "is best\n")

Mysore is best


In [88]:
message <- "Programiz"
cat("Welcome to ", message)

Welcome to  Programiz

In [100]:
## print multiple values in statements

r = 10.2
interest= 103

cat("Hi Interes",r,"value",interest)

Hi Interes 10.2 value 103

# Variables

In [1]:
# Variable assignment

    myString <- "Santhosh" # or myString = "Santhosh"
    print(myString)

    x <- 45
    print(x)

[1] "Santhosh"
[1] 45


# Data Types

In [3]:
# Data type : logical
    v <- TRUE
    print(class(v))

[1] "logical"


In [4]:
# Data type : Numeric
    num <-23.5
    print(class(num))

[1] "numeric"


In [5]:
# Data type : Integer
    num1 <- 2L
    print(class(num1))

[1] "integer"


In [10]:
# Data type : Character
    myString <- "Santhosh"
    class(myString)

[1] "character"

# Vector or List

In [65]:
# Vectors / list creation

    colors <- c('red','green',"yellow")

In [66]:
# get the elements of vector on index wise    
    print(colors[2])

[1] "green"


In [67]:
# Append the values in vector    

    colors<- append(colors, 'black')

    colors

[1] "red"    "green"  "yellow" "black"

In [68]:
# Append at specific positions (1st Postion)

    colors<- append(colors, 'pink', 1)

    colors

[1] "red"    "pink"   "green"  "yellow" "black"

In [69]:
    # Remove item from list based on index value

    colors[-3]

[1] "red"    "pink"   "yellow" "black"

In [71]:
   # Remove multiple Items frm list
     colors[c(-1,-3)]

[1] "pink"   "yellow" "black"

## List Comprehension

In [62]:
require(foreach)

list_a = c(1, 2, 3)
list_b = c(2,7)

different_num  <- foreach(a=list_a) %:% foreach(b=list_b) %:% when(a!=b) %do% sum(a,b)

different_num

[[1]]
[[1]][[1]]
[1] 3

[[1]][[2]]
[1] 8


[[2]]
[[2]][[1]]
[1] 9


[[3]]
[[3]][[1]]
[1] 5

[[3]][[2]]
[1] 10

In [102]:
library(foreach)

val = c(1,2,3,4,5)

foreach(i=val) %do% sqrt(i)

[[1]]
[1] 1

[[2]]
[1] 1.414214

[[3]]
[1] 1.732051

[[4]]
[1] 2

[[5]]
[1] 2.236068

In [103]:
val1 = c(1,2,3,4,5)
val2 = c(1,2,3,4,5)

foreach(i=val1,j=val2) %do% (i*j)

[[1]]
[1] 1

[[2]]
[1] 4

[[3]]
[1] 9

[[4]]
[1] 16

[[5]]
[1] 25

In [104]:
foreach(i=val) %do% (i*i)

[[1]]
[1] 1

[[2]]
[1] 4

[[3]]
[1] 9

[[4]]
[1] 16

[[5]]
[1] 25

# Matrix

In [43]:
# Create Matrix
    M = matrix(c(1,2,3,4,5,6),nrow = 3,ncol = 2,byrow = TRUE)
    M

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6

In [39]:
    matrix(1:10, ncol = 2)

[,1] [,2]
[1,] 1     6  
[2,] 2     7  
[3,] 3     8  
[4,] 4     9  
[5,] 5    10

In [40]:
    vector1=1:9
    matrix(vector1, nrow = 3)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [42]:
#  create a matrix of zeros
    zero_matrix <- matrix(rep(0, 9),ncol = 3, nrow = 3)

    zero_matrix

[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 0    0    0   
[3,] 0    0    0

In [44]:
# Check the dimention of the matrix

    dim(M)

[1] 3 2

In [1]:
    matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9), nrow = 3)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [2]:
    matrix(1:10, ncol = 2)

[,1] [,2]
[1,] 1     6  
[2,] 2     7  
[3,] 3     8  
[4,] 4     9  
[5,] 5    10

In [3]:
    vector1=1:9
    matrix(vector1, nrow = 3)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [4]:
matrix1 = matrix(vector1, nrow = 3)
matrix2=matrix1 + 2
matrix2

[,1] [,2] [,3]
[1,] 3    6     9  
[2,] 4    7    10  
[3,] 5    8    11

In [5]:
matrix2 - matrix1 # Subtraction of two matrices

[,1] [,2] [,3]
[1,] 2    2    2   
[2,] 2    2    2   
[3,] 2    2    2

In [6]:
matrix1 * matrix2

[,1] [,2] [,3]
[1,]  3   24   63  
[2,]  8   35   80  
[3,] 15   48   99

In [7]:
t(matrix1)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [8]:
rbind(matrix1,matrix2)

[,1] [,2] [,3]
[1,] 1    4     7  
[2,] 2    5     8  
[3,] 3    6     9  
[4,] 3    6     9  
[5,] 4    7    10  
[6,] 5    8    11

In [9]:
cbind(matrix1,matrix2)

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    4    7    3    6     9  
[2,] 2    5    8    4    7    10  
[3,] 3    6    9    5    8    11

# Factors

In [ ]:
# It stores the vector along with the distinct values of the elements in the vector as labels.

In [53]:
apple_colors <- c('green','green','yellow','red','red','red','green')

factor_apple <- factor(apple_colors)

levels(factor_apple)

[1] "green"  "red"    "yellow"

In [54]:
print(nlevels(factor_apple))

[1] 3


# Lists

In [10]:
# While vectors and matrices/arrays can hold only data of a single type, while lists and data frames can combine data of 
# different types.

In [11]:
x<-list(1,2,5.6,8,4)
x

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 5.6

[[4]]
[1] 8

[[5]]
[1] 4

In [12]:
y=list(3:10)
y

[[1]]
[1]  3  4  5  6  7  8  9 10

In [13]:
z=list("Apple","Orange","Grapes","Jackfruit")
z

[[1]]
[1] "Apple"

[[2]]
[1] "Orange"

[[3]]
[1] "Grapes"

[[4]]
[1] "Jackfruit"

In [14]:
x <- list(1:5, TRUE, "Fruits", list(1:3, 5))
x

[[1]]
[1] 1 2 3 4 5

[[2]]
[1] TRUE

[[3]]
[1] "Fruits"

[[4]]
[[4]][[1]]
[1] 1 2 3

[[4]][[2]]
[1] 5

In [16]:
# Here x has 4 elements: a numeric vector, a logical, a string and another list. 
# We can select an entry of x with double square brackets:

x[[2]]

[1] TRUE

In [17]:
x[c(1,4)]

[[1]]
[1] 1 2 3 4 5

[[2]]
[[2]][[1]]
[1] 1 2 3

[[2]][[2]]
[1] 5

In [18]:
course <- list(name="Introduction to AI and Data Science",level=c("masters","PhD"),
date=list(from="August 1",to="December 31"),maxnumber=25)
course

$name
[1] "Introduction to AI and Data Science"

$level
[1] "masters" "PhD"    

$date
$date$from
[1] "August 1"

$date$to
[1] "December 31"


$maxnumber
[1] 25

In [19]:
names(course)

[1] "name"      "level"     "date"      "maxnumber"

In [20]:
course$No_of_Hours <-45 
course

$name
[1] "Introduction to AI and Data Science"

$level
[1] "masters" "PhD"    

$date
$date$from
[1] "August 1"

$date$to
[1] "December 31"


$maxnumber
[1] 25

$No_of_Hours
[1] 45

In [21]:
course$level<- NULL
course

$name
[1] "Introduction to AI and Data Science"

$date
$date$from
[1] "August 1"

$date$to
[1] "December 31"


$maxnumber
[1] 25

$No_of_Hours
[1] 45

In [ ]:
# The unlist() function is used to convert a list to vector in R. Th
# The unlist() function takes the list as an argument and returns the Vector.

In [22]:
course1<-unlist(course)
course1

name                             date.from 
"Introduction to AI and Data Science"                            "August 1" 
                              date.to                             maxnumber 
                        "December 31"                                  "25" 
                          No_of_Hours 
                                 "45"

In [23]:
list1=(1:7)
list2=(14:20)
data <- list(list1,list2)
arr <- array(as.numeric(unlist(data)), dim = c(4, 4,3))
arr

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    5   15   19
[2,]    2    6   16   20
[3,]    3    7   17    1
[4,]    4   14   18    2

, , 2

     [,1] [,2] [,3] [,4]
[1,]    3    7   17    1
[2,]    4   14   18    2
[3,]    5   15   19    3
[4,]    6   16   20    4

, , 3

     [,1] [,2] [,3] [,4]
[1,]    5   15   19    3
[2,]    6   16   20    4
[3,]    7   17    1    5
[4,]   14   18    2    6